name: mocl_flutter
description: "Mocl Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.0+361

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # HTML 파서
  html: ^0.15.4
  # HTML Widget
  flutter_widget_from_html: ^0.15.2
  # Service locator
  injectable: ^2.4.4
  get_it: ^7.7.0
  # Bloc for state management
  flutter_bloc: ^8.1.6
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  #  dartz: ^0.10.1
  # Remote API
  #  internet_connection_checker_plus: ^2.4.2
  # Http Client
  #  http: ^1.2.2
  dio: ^5.6.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  # Local cache
  shared_preferences: ^2.2.3
  # json
  json_annotation: ^4.9.0
  # Path
  path_provider: ^2.1.3
  # class 자동화
  freezed_annotation: ^2.4.1
  # 무한 스크롤 리스트
  infinite_scroll_pagination: ^4.0.0
  # 이미지 캐시
  cached_network_image: ^3.4.0
  #  image: ^4.2.0
  #  flutter_cache_manager: ^3.4.1
  # URL 런처
  url_launcher: ^6.3.0
  # swipe back
  #cupertino_back_gesture: ^0.1.0
  swipeable_page_route: ^0.4.4
  flutter_native_splash: ^2.4.1
  #  gif: ^2.3.0
  # like room database
  floor: ^1.5.0

  go_router: ^14.2.6

  firebase_crashlytics: ^4.1.0
  async: ^2.11.0

#  flutter_isolate: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  #  isar_generator: ^3.1.0+1
  freezed: ^2.5.2
  analyzer: ^6.7.0
  test: ^1.25.7
  bloc_test: ^9.1.7
  floor_generator: ^1.5.0
#  riverpod_generator: ^2.4.2
#  riverpod_lint: ^2.3.12
  injectable_generator: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/damoang/
    - assets/clien/
    - assets/icon.png
