name: mocl_flutter
description: "Mocl Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.0+370

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
#  cupertino_icons: ^1.0.8

  # HTML 파서
  html: ^0.15.5+1

  # HTML Widget
  flutter_widget_from_html: ^0.17.0

  # DI
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Bloc for state management
  flutter_bloc: ^9.1.1

  # Value equality
  equatable: ^2.0.7

  # Functional programming thingies
  #  dartz: ^0.10.1
  # Remote API
  #  internet_connection_checker_plus: ^2.4.2
  # Http Client
  #  http: ^1.2.2
  dio: ^5.8.0+1

  # cookie
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0

  # Local cache
  shared_preferences: ^2.5.3

  # json
  json_annotation: ^4.9.0

  # Path
  path_provider: ^2.1.5

  # class 자동화
  freezed_annotation: ^3.1.0

  # 이미지 캐시
  cached_network_image: ^3.4.1
  # image: ^4.2.0
  flutter_cache_manager: ^3.4.1

  # URL 런처
  url_launcher: ^6.3.2

  # swipe back
  swipeable_page_route: ^0.4.7

  # splash
#  flutter_native_splash: ^2.4.4
  #  gif: ^2.3.0
  # like room database
#  floor: ^1.5.0
  #  hive_flutter: ^1.1.0

  # router
  go_router: ^16.0.0

  # firebase
  firebase_crashlytics: ^4.3.10

  # async
#  async: ^2.12.0

  # infinite pagination
#  easy_infinite_pagination: ^0.0.6
#  flutter_isolate: ^2.0.4
  infinite_scroll_pagination: ^5.1.0

  # share
  share_plus: ^11.0.0
#  share_plus_platform_interface: ^6.0.0

  # package info
  package_info_plus: ^8.3.0

  # time format
  timeago: ^3.7.1

  # like crashlytics..
#  sentry_flutter: ^8.14.2

  # sliver tools
  sliver_tools: ^0.2.12

  # toast
  fluttertoast: ^8.2.12

  flutter_inappwebview: ^6.1.5
#  webview_flutter: ^4.10.0

  photo_view: ^0.15.0

  dartx: ^1.2.0

  easy_debounce: ^2.0.3

#dependency_overrides:
#  flutter_color_models: '1.2.1'
#  color_models: '1.2.1'

  # nosql
  sembast: ^3.8.5+1

  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.2
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  freezed: ^3.0.6
  analyzer: ^7.4.5
#  test: ^1.25.15
  bloc_test: ^10.0.0
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/damoang/
    - assets/clien/
    - assets/meeco/
    - assets/navercafe/
    - assets/reddit/
    - assets/theqoo/
