name: mocl_flutter
description: "Mocl Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  html: ^0.15.4
  flutter_widget_from_html: ^0.15.1
  # Service locator
  get_it: ^7.7.0
  # Bloc for state management
  flutter_bloc: ^8.1.6
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Remote API
#  data_connection_checker: ^0.3.4
  internet_connection_checker_plus: ^2.4.2
  http: ^1.2.1
  # Local cache
  shared_preferences: ^2.2.3
  # json
  json_annotation: ^4.9.0

  # NoSQL
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

  path_provider: ^2.1.3
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_storage: ^2.1.1
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1

  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
#  hive_generator: ^2.0.1
  mockito: ^5.4.4
  isar_generator: ^3.1.0
  freezed: ^2.5.2
  analyzer: ^5.13.0
  test: ^1.25.2
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/damoang/
    - assets/clien/
