name: mocl_flutter
description: "Mocl Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.0+361

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: ^1.0.8

  # HTML 파서
  html: ^0.15.5

  # HTML Widget
  flutter_widget_from_html: ^0.15.2

  # DI
  injectable: ^2.5.0
  get_it: ^8.0.2

  # Bloc for state management
  flutter_bloc: ^8.1.6

  # Value equality
  equatable: ^2.0.5

  # Functional programming thingies
  #  dartz: ^0.10.1
  # Remote API
  #  internet_connection_checker_plus: ^2.4.2
  # Http Client
  #  http: ^1.2.2
  dio: ^5.7.0

  # cookie
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1

  # Local cache
  shared_preferences: ^2.3.3

  # json
  json_annotation: ^4.9.0

  # Path
  path_provider: ^2.1.5

  # class 자동화
  freezed_annotation: ^2.4.4

  # 이미지 캐시
  cached_network_image: ^3.4.1
  #  image: ^4.2.0
  flutter_cache_manager: ^3.4.1

  # URL 런처
  url_launcher: ^6.3.1

  # swipe back
  swipeable_page_route: ^0.4.4

  # splash
  flutter_native_splash: ^2.4.2
  #  gif: ^2.3.0
  # like room database
  floor: ^1.5.0
  #  hive_flutter: ^1.1.0

  # router
  go_router: ^14.4.1

  # firebase
  firebase_crashlytics: ^4.1.4

  # async
  async: ^2.11.0

  # infinite pagination
  easy_infinite_pagination: ^0.0.6
#  flutter_isolate: ^2.0.4

  # share
  share_plus: ^10.1.2
  share_plus_platform_interface: ^5.0.1

  # package info
  package_info_plus: ^8.1.1

  # time format
  timeago: ^3.7.0

  # like crashlytics..
  sentry_flutter: ^8.10.1

  # change app name
  launcher_name: ^1.0.2

  # sliver tools
  sliver_tools: ^0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  freezed: ^2.5.7
  analyzer: ^6.7.0
  test: ^1.25.7
  bloc_test: ^9.1.7
  floor_generator: ^1.5.0
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/damoang/
    - assets/clien/
    - assets/meeco/
    - assets/navercafe/
    - assets/icon.png

launcher_name:
  default: "Mocl"
