[package]
name = "mocl_parser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
scraper = "0.20"
once_cell = "1"
regex = "1"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = 3

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
