// Mocks generated by Mockito 5.4.4 from annotations
// in mocl_flutter/test/features/mocl/data/repositories/mocl_main_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:mocl_flutter/features/mocl/data/datasources/main_data_source.dart'
    as _i4;
import 'package:mocl_flutter/features/mocl/data/datasources/remote/base/base_api.dart'
    as _i3;
import 'package:mocl_flutter/features/mocl/data/datasources/remote/base/base_parser.dart'
    as _i2;
import 'package:mocl_flutter/features/mocl/data/datasources/remote/parser/parser_factory.dart'
    as _i12;
import 'package:mocl_flutter/features/mocl/data/models/main_item_model.dart'
    as _i10;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_main_item.dart'
    as _i7;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_result.dart'
    as _i6;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_site_type.dart'
    as _i8;
import 'package:mocl_flutter/features/mocl/domain/repositories/settings_repository.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseParser_0 extends _i1.SmartFake implements _i2.BaseParser {
  _FakeBaseParser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseApi_1 extends _i1.SmartFake implements _i3.BaseApi {
  _FakeBaseApi_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MainDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMainDataSource extends _i1.Mock implements _i4.MainDataSource {
  MockMainDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Result<List<_i7.MainItem>>> get(_i8.SiteType? siteType) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [siteType],
        ),
        returnValue: _i5.Future<_i6.Result<List<_i7.MainItem>>>.value(
            _i9.dummyValue<_i6.Result<List<_i7.MainItem>>>(
          this,
          Invocation.method(
            #get,
            [siteType],
          ),
        )),
      ) as _i5.Future<_i6.Result<List<_i7.MainItem>>>);

  @override
  _i5.Future<List<int>> set(
    _i8.SiteType? siteType,
    List<_i7.MainItem>? list,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #set,
          [
            siteType,
            list,
          ],
        ),
        returnValue: _i5.Future<List<int>>.value(<int>[]),
      ) as _i5.Future<List<int>>);

  @override
  _i5.Future<List<_i10.MainItemModel>> getAllFromJson(_i8.SiteType? siteType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllFromJson,
          [siteType],
        ),
        returnValue:
            _i5.Future<List<_i10.MainItemModel>>.value(<_i10.MainItemModel>[]),
      ) as _i5.Future<List<_i10.MainItemModel>>);

  @override
  _i5.Future<void> deleteAll(_i8.SiteType? siteType) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [siteType],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> hasItem(
    _i8.SiteType? siteType,
    _i7.MainItem? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasItem,
          [
            siteType,
            item,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i11.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.SiteType getSiteType() => (super.noSuchMethod(
        Invocation.method(
          #getSiteType,
          [],
        ),
        returnValue: _i8.SiteType.clien,
      ) as _i8.SiteType);

  @override
  void setSiteType(_i8.SiteType? siteType) => super.noSuchMethod(
        Invocation.method(
          #setSiteType,
          [siteType],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [ParserFactory].
///
/// See the documentation for Mockito's code generation for more information.
class MockParserFactory extends _i1.Mock implements _i12.ParserFactory {
  MockParserFactory() {
    _i1.throwOnMissingStub(this);
  }

  @override
  (_i2.BaseParser, _i3.BaseApi) buildParser() => (super.noSuchMethod(
        Invocation.method(
          #buildParser,
          [],
        ),
        returnValue: (
          _FakeBaseParser_0(
            this,
            Invocation.method(
              #buildParser,
              [],
            ),
          ),
          _FakeBaseApi_1(
            this,
            Invocation.method(
              #buildParser,
              [],
            ),
          )
        ),
      ) as (_i2.BaseParser, _i3.BaseApi));
}
