[versions]
agp = "8.7.3"
kotlin = "2.0.20"
flutterPlugin = "1.0.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
flutterPluginLoader = { id = "dev.flutter.flutter-plugin-loader", version.ref = "flutterPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }