// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpk_I540mTeQn93E0FA6RUyd06fXU-XXg',
    appId: '1:275270612301:web:6dc1871cb62af6de123304',
    messagingSenderId: '275270612301',
    projectId: 'mocl-b418e',
    authDomain: 'mocl-b418e.firebaseapp.com',
    databaseURL: 'https://mocl-b418e.firebaseio.com',
    storageBucket: 'mocl-b418e.appspot.com',
    measurementId: 'G-EWYX47PVFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKmRddEbS0zM7PodXDOvtAEdJl6-qk3pk',
    appId: '1:275270612301:android:6b15e1c81167409a',
    messagingSenderId: '275270612301',
    projectId: 'mocl-b418e',
    databaseURL: 'https://mocl-b418e.firebaseio.com',
    storageBucket: 'mocl-b418e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo8cW-g5I7BltfZZ5qSh65RRdDtdJitco',
    appId: '1:275270612301:ios:0cc80825e1e542a2123304',
    messagingSenderId: '275270612301',
    projectId: 'mocl-b418e',
    databaseURL: 'https://mocl-b418e.firebaseio.com',
    storageBucket: 'mocl-b418e.appspot.com',
    androidClientId: '275270612301-3jajhso3ce2c9ungjkgifi3em060uupa.apps.googleusercontent.com',
    iosBundleId: 'net.b1ink.moclFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo8cW-g5I7BltfZZ5qSh65RRdDtdJitco',
    appId: '1:275270612301:ios:0cc80825e1e542a2123304',
    messagingSenderId: '275270612301',
    projectId: 'mocl-b418e',
    databaseURL: 'https://mocl-b418e.firebaseio.com',
    storageBucket: 'mocl-b418e.appspot.com',
    androidClientId: '275270612301-3jajhso3ce2c9ungjkgifi3em060uupa.apps.googleusercontent.com',
    iosBundleId: 'net.b1ink.moclFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpk_I540mTeQn93E0FA6RUyd06fXU-XXg',
    appId: '1:275270612301:web:3f5038f71c246393123304',
    messagingSenderId: '275270612301',
    projectId: 'mocl-b418e',
    authDomain: 'mocl-b418e.firebaseapp.com',
    databaseURL: 'https://mocl-b418e.firebaseio.com',
    storageBucket: 'mocl-b418e.appspot.com',
    measurementId: 'G-2NZHP490Q5',
  );
}
