// Mocks generated by Mockito 5.4.6 from annotations
// in mocl_flutter/test/features/mocl/data/datasoures/mocl_list_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:mocl_flutter/core/data/datasources/list_data_source.dart'
    as _i2;
import 'package:mocl_flutter/core/data/datasources/remote/base/base_parser.dart'
    as _i11;
import 'package:mocl_flutter/core/domain/entities/last_id.dart' as _i7;
import 'package:mocl_flutter/core/domain/entities/mocl_comment_item.dart'
    as _i14;
import 'package:mocl_flutter/core/domain/entities/mocl_details.dart' as _i13;
import 'package:mocl_flutter/core/domain/entities/mocl_list_item.dart' as _i5;
import 'package:mocl_flutter/core/domain/entities/mocl_main_item.dart' as _i6;
import 'package:mocl_flutter/core/domain/entities/mocl_result.dart' as _i4;
import 'package:mocl_flutter/core/domain/entities/mocl_site_type.dart' as _i10;
import 'package:mocl_flutter/core/domain/entities/sort_type.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ListDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockListDataSource extends _i1.Mock implements _i2.ListDataSource {
  MockListDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ListItem>>> getList(
    _i6.MainItem? item,
    int? page,
    _i7.LastId? lastId,
    _i8.SortType? sortType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getList, [item, page, lastId, sortType]),
            returnValue: _i3.Future<_i4.Result<List<_i5.ListItem>>>.value(
              _i9.dummyValue<_i4.Result<List<_i5.ListItem>>>(
                this,
                Invocation.method(#getList, [item, page, lastId, sortType]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ListItem>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.ListItem>>> getSearchList(
    _i6.MainItem? item,
    int? page,
    _i7.LastId? lastId,
    _i8.SortType? sortType,
    String? keyword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSearchList, [
              item,
              page,
              lastId,
              sortType,
              keyword,
            ]),
            returnValue: _i3.Future<_i4.Result<List<_i5.ListItem>>>.value(
              _i9.dummyValue<_i4.Result<List<_i5.ListItem>>>(
                this,
                Invocation.method(#getSearchList, [
                  item,
                  page,
                  lastId,
                  sortType,
                  keyword,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ListItem>>>);

  @override
  _i3.Future<int> setReadFlag(_i10.SiteType? siteType, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#setReadFlag, [siteType, id]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<bool> isReadFlag(_i10.SiteType? siteType, int? boardId) =>
      (super.noSuchMethod(
            Invocation.method(#isReadFlag, [siteType, boardId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<List<int>> isReadFlags(
    _i10.SiteType? siteType,
    List<int>? boardIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isReadFlags, [siteType, boardIds]),
            returnValue: _i3.Future<List<int>>.value(<int>[]),
          )
          as _i3.Future<List<int>>);
}

/// A class which mocks [BaseParser].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseParser extends _i1.Mock implements _i11.BaseParser {
  MockBaseParser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.SiteType get siteType =>
      (super.noSuchMethod(
            Invocation.getter(#siteType),
            returnValue: _i10.SiteType.clien,
          )
          as _i10.SiteType);

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String urlByMain() =>
      (super.noSuchMethod(
            Invocation.method(#urlByMain, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#urlByMain, []),
            ),
          )
          as String);

  @override
  String urlByList(
    String? url,
    String? board,
    int? page,
    _i8.SortType? sortType,
    _i7.LastId? lastId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#urlByList, [url, board, page, sortType, lastId]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#urlByList, [
                url,
                board,
                page,
                sortType,
                lastId,
              ]),
            ),
          )
          as String);

  @override
  String urlBySearchList(
    String? url,
    String? board,
    int? page,
    String? keyword,
    _i7.LastId? lastId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#urlBySearchList, [
              url,
              board,
              page,
              keyword,
              lastId,
            ]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#urlBySearchList, [
                url,
                board,
                page,
                keyword,
                lastId,
              ]),
            ),
          )
          as String);

  @override
  String urlByDetail(String? url, String? board, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#urlByDetail, [url, board, id]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#urlByDetail, [url, board, id]),
            ),
          )
          as String);

  @override
  String urlByComments(String? url, String? board, int? id, int? page) =>
      (super.noSuchMethod(
            Invocation.method(#urlByComments, [url, board, id, page]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#urlByComments, [url, board, id, page]),
            ),
          )
          as String);

  @override
  _i3.Future<_i4.Result<List<_i6.MainItem>>> main(
    _i12.Response<dynamic>? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#main, [response]),
            returnValue: _i3.Future<_i4.Result<List<_i6.MainItem>>>.value(
              _i9.dummyValue<_i4.Result<List<_i6.MainItem>>>(
                this,
                Invocation.method(#main, [response]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i6.MainItem>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.ListItem>>> list(
    _i12.Response<dynamic>? response,
    _i7.LastId? lastId,
    String? boardTitle,
    _i3.Future<List<int>> Function(_i10.SiteType, List<int>)? isReads,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#list, [response, lastId, boardTitle, isReads]),
            returnValue: _i3.Future<_i4.Result<List<_i5.ListItem>>>.value(
              _i9.dummyValue<_i4.Result<List<_i5.ListItem>>>(
                this,
                Invocation.method(#list, [
                  response,
                  lastId,
                  boardTitle,
                  isReads,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.ListItem>>>);

  @override
  _i3.Future<_i4.Result<_i13.Details>> detail(
    _i12.Response<dynamic>? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#detail, [response]),
            returnValue: _i3.Future<_i4.Result<_i13.Details>>.value(
              _i9.dummyValue<_i4.Result<_i13.Details>>(
                this,
                Invocation.method(#detail, [response]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i13.Details>>);

  @override
  _i3.Future<_i4.Result<List<_i14.CommentItem>>> comments(
    _i12.Response<dynamic>? response,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#comments, [response]),
            returnValue: _i3.Future<_i4.Result<List<_i14.CommentItem>>>.value(
              _i9.dummyValue<_i4.Result<List<_i14.CommentItem>>>(
                this,
                Invocation.method(#comments, [response]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i14.CommentItem>>>);
}
