// Mocks generated by Mockito 5.4.5 from annotations
// in mocl_flutter/test/features/mocl/data/datasoures/mocl_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cookie_jar/cookie_jar.dart' as _i9;
import 'package:dio/dio.dart' as _i2;
import 'package:fpdart/fpdart.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:mocl_flutter/core/error/failures.dart' as _i11;
import 'package:mocl_flutter/features/mocl/data/datasources/local/entities/main_item_data.dart'
    as _i5;
import 'package:mocl_flutter/features/mocl/data/datasources/local/local_database.dart'
    as _i3;
import 'package:mocl_flutter/features/mocl/data/datasources/remote/base/base_api.dart'
    as _i7;
import 'package:mocl_flutter/features/mocl/data/datasources/remote/base/base_parser.dart'
    as _i13;
import 'package:mocl_flutter/features/mocl/domain/entities/last_id.dart'
    as _i16;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_comment_item.dart'
    as _i18;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_details.dart'
    as _i14;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_list_item.dart'
    as _i15;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_main_item.dart'
    as _i12;
import 'package:mocl_flutter/features/mocl/domain/entities/mocl_site_type.dart'
    as _i6;
import 'package:mocl_flutter/features/mocl/domain/entities/sort_type.dart'
    as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalDatabase extends _i1.Mock implements _i3.LocalDatabase {
  MockLocalDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.MainItemData>> getMainData(_i6.SiteType? siteType) =>
      (super.noSuchMethod(
            Invocation.method(#getMainData, [siteType]),
            returnValue: _i4.Future<List<_i5.MainItemData>>.value(
              <_i5.MainItemData>[],
            ),
          )
          as _i4.Future<List<_i5.MainItemData>>);

  @override
  _i4.Future<List<int>> setMainData(
    _i6.SiteType? siteType,
    List<_i5.MainItemData>? entities,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setMainData, [siteType, entities]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.Future<List<int>>);

  @override
  _i4.Future<void> deleteAll(_i6.SiteType? siteType) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [siteType]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasItem(_i6.SiteType? siteType, _i5.MainItemData? entity) =>
      (super.noSuchMethod(
            Invocation.method(#hasItem, [siteType, entity]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isRead(_i6.SiteType? siteType, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isRead, [siteType, id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.FutureOr<List<int>> isReads(_i6.SiteType? siteType, List<int>? ids) =>
      (super.noSuchMethod(
            Invocation.method(#isReads, [siteType, ids]),
            returnValue: _i4.Future<List<int>>.value(<int>[]),
          )
          as _i4.FutureOr<List<int>>);

  @override
  _i4.Future<int> setRead(_i6.SiteType? siteType, int? id) =>
      (super.noSuchMethod(
            Invocation.method(#setRead, [siteType, id]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BaseApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseApi extends _i1.Mock implements _i7.BaseApi {
  MockBaseApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  void init(_i9.CookieJar? cookieJar) => super.noSuchMethod(
    Invocation.method(#init, [cookieJar]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.Response<dynamic>> getUri(
    Uri? uri, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUri, [uri], {#headers: headers}),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(#getUri, [uri], {#headers: headers}),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> get(
    String? url, {
    Map<String, String>? headers,
    _i2.ResponseType? responseType,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [url],
              {
                #headers: headers,
                #responseType: responseType,
                #contentType: contentType,
              },
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #headers: headers,
                    #responseType: responseType,
                    #contentType: contentType,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i2.Response<dynamic>> postUri(
    String? url, {
    Map<String, String>? headers,
    Object? data,
    _i2.ResponseType? responseType,
    String? contentType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [url],
              {
                #headers: headers,
                #data: data,
                #responseType: responseType,
                #contentType: contentType,
              },
            ),
            returnValue: _i4.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #postUri,
                  [url],
                  {
                    #headers: headers,
                    #data: data,
                    #responseType: responseType,
                    #contentType: contentType,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response<dynamic>>);

  @override
  _i4.Future<_i10.Either<_i11.Failure, T>> withSyncCookie<T>(
    String? baseUrl,
    _i4.Future<_i10.Either<_i11.Failure, T>> Function()? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#withSyncCookie, [baseUrl, action]),
            returnValue: _i4.Future<_i10.Either<_i11.Failure, T>>.value(
              _i8.dummyValue<_i10.Either<_i11.Failure, T>>(
                this,
                Invocation.method(#withSyncCookie, [baseUrl, action]),
              ),
            ),
          )
          as _i4.Future<_i10.Either<_i11.Failure, T>>);

  @override
  _i4.Future<_i10.Either<_i11.Failure, List<_i12.MainItem>>> main(
    _i13.BaseParser? parser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#main, [parser]),
            returnValue: _i4.Future<
              _i10.Either<_i11.Failure, List<_i12.MainItem>>
            >.value(
              _i8.dummyValue<_i10.Either<_i11.Failure, List<_i12.MainItem>>>(
                this,
                Invocation.method(#main, [parser]),
              ),
            ),
          )
          as _i4.Future<_i10.Either<_i11.Failure, List<_i12.MainItem>>>);

  @override
  _i4.Future<_i10.Either<_i11.Failure, _i14.Details>> detail(
    _i15.ListItem? item,
    _i13.BaseParser? parser,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#detail, [item, parser]),
            returnValue:
                _i4.Future<_i10.Either<_i11.Failure, _i14.Details>>.value(
                  _i8.dummyValue<_i10.Either<_i11.Failure, _i14.Details>>(
                    this,
                    Invocation.method(#detail, [item, parser]),
                  ),
                ),
          )
          as _i4.Future<_i10.Either<_i11.Failure, _i14.Details>>);

  @override
  _i4.Future<_i10.Either<_i11.Failure, List<_i15.ListItem>>> list(
    _i12.MainItem? item,
    int? page,
    _i16.LastId? lastId,
    _i17.SortType? sortType,
    _i13.BaseParser? parser,
    _i4.Future<List<int>> Function(_i6.SiteType, List<int>)? isReads,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#list, [
              item,
              page,
              lastId,
              sortType,
              parser,
              isReads,
            ]),
            returnValue: _i4.Future<
              _i10.Either<_i11.Failure, List<_i15.ListItem>>
            >.value(
              _i8.dummyValue<_i10.Either<_i11.Failure, List<_i15.ListItem>>>(
                this,
                Invocation.method(#list, [
                  item,
                  page,
                  lastId,
                  sortType,
                  parser,
                  isReads,
                ]),
              ),
            ),
          )
          as _i4.Future<_i10.Either<_i11.Failure, List<_i15.ListItem>>>);

  @override
  _i4.Future<_i10.Either<_i11.Failure, List<_i15.ListItem>>> searchList(
    _i12.MainItem? item,
    int? page,
    _i16.LastId? lastId,
    _i17.SortType? sortType,
    String? keyword,
    _i13.BaseParser? parser,
    _i4.Future<List<int>> Function(_i6.SiteType, List<int>)? isReads,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchList, [
              item,
              page,
              lastId,
              sortType,
              keyword,
              parser,
              isReads,
            ]),
            returnValue: _i4.Future<
              _i10.Either<_i11.Failure, List<_i15.ListItem>>
            >.value(
              _i8.dummyValue<_i10.Either<_i11.Failure, List<_i15.ListItem>>>(
                this,
                Invocation.method(#searchList, [
                  item,
                  page,
                  lastId,
                  sortType,
                  keyword,
                  parser,
                  isReads,
                ]),
              ),
            ),
          )
          as _i4.Future<_i10.Either<_i11.Failure, List<_i15.ListItem>>>);

  @override
  _i4.Future<_i10.Either<_i11.Failure, List<_i18.CommentItem>>> comments(
    _i15.ListItem? item,
    _i13.BaseParser? parser,
    int? page,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#comments, [item, parser, page]),
            returnValue: _i4.Future<
              _i10.Either<_i11.Failure, List<_i18.CommentItem>>
            >.value(
              _i8.dummyValue<_i10.Either<_i11.Failure, List<_i18.CommentItem>>>(
                this,
                Invocation.method(#comments, [item, parser, page]),
              ),
            ),
          )
          as _i4.Future<_i10.Either<_i11.Failure, List<_i18.CommentItem>>>);
}
